---
title: "tidy_text"
output: html_document
---

```{r}
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)

library(tidytext)
library(rvest)
```

## Data

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>% 
  filter(grade %in% c("A", "B", "C")) %>% 
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro)) %>% 
  select(inspection_num, boro, grade, score, critical_flag, dba, cuisine_description, zipcode, violation_description)
```

## Words and Wordcounts

```{r}
#each word has its own row
inspection_words = 
  rest_inspec %>% 
  unnest_tokens(word, violation_description)
```

```{r}
#remove all the meaningless words
data(stop_words)

inspection_words = 
  anti_join(inspection_words, stop_words)
```

count some words

```{r}
inspection_words %>% 
  count(word, sort = TRUE) %>% 
  top_n(10) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) + 
  geom_bar(stat = "identity", fill = "blue", alpha = .6) + 
  coord_flip()
```

```{r}
#see how many times each word appears in A and C grades annd then calculate the log odds
word_ratios = 
  inspection_words %>%
  filter(grade %in% c("A", "C")) %>% 
  count(word, grade) %>%
  group_by(word) %>% 
  filter(sum(n) >= 5) %>%
  ungroup() %>%
  spread(grade, n, fill = 0) %>%
  mutate(
    C_odds = (C + 1) / (sum(C) + 1),
    A_odds = (A + 1) / (sum(A) + 1),
    log_OR = log(C_odds / A_odds)
  ) %>%
  arrange(desc(log_OR)) 
```


```{r}
word_ratios %>%
  mutate(pos_log_OR = ifelse(log_OR > 0, "C > A", "A > C")) %>% 
  group_by(pos_log_OR) %>%
  top_n(15, abs(log_OR)) %>%
  ungroup() %>%
  mutate(word = fct_reorder(word, log_OR)) %>%
  ggplot(aes(word, log_OR, fill = pos_log_OR)) +
  geom_col() +
  coord_flip() +
  ylab("log odds ratio (C/A)") +
  scale_fill_discrete(name = "")
```

## Sentiment analysis

```{r}
#tells you if word is positive vs negative
bing_sentiments = get_sentiments("bing")
```

```{r}
#calculates a sentiment score for each inspection number; how positive or negative is each overall description?
inspection_sentiments = 
  inspection_words %>% 
  inner_join(., bing_sentiments) %>% 
  count(inspection_num, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  select(inspection_num, sentiment)
```

```{r}
inspection_sentiments = 
  right_join(rest_inspec, inspection_sentiments, 
             by = "inspection_num")
```

```{r}
set.seed(1)

inspection_sentiments %>% 
  filter(boro == "Manhattan") %>% 
  sample_n(5000) %>% 
  mutate(inspection_num = factor(inspection_num),
    inspection_num = fct_reorder(inspection_num, sentiment)) %>% 
  ggplot(aes(x = inspection_num, 
             y = sentiment, fill = grade, color = grade)) + 
  geom_bar(stat = "identity") + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_fill_viridis(discrete = TRUE) + 
  scale_color_viridis(discrete = TRUE) 
```


## Napoleon

```{r}
read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

dynamite_reviews = 
  tibble(page = 1:100,
         urls = str_c(url_base, page)) %>% 
  mutate(reviews = map(urls, read_page_reviews)) %>% 
  unnest()
```

remove stop words

```{r}
dynamite_reviews = 
  dynamite_reviews %>%
  as_tibble() %>%
  mutate(review_num = row_number())

data(stop_words)

dynamite_words = 
  dynamite_reviews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  arrange(review_num)
```

Table of most frequently used words in 1 and 5 star reviews

```{r}
dynamite_words %>%
  filter(stars %in% c(1, 5)) %>%
  group_by(stars) %>%
  count(word) %>% 
  top_n(5) %>%
  knitr::kable()
```

Plot log odds

```{r}
word_ratios <- dynamite_words %>%
    filter(stars %in% c(1, 5)) %>% 
    count(word, stars) %>%
    group_by(word) %>% 
    filter(sum(n) >= 3) %>%
    ungroup() %>%
    spread(stars, n, fill = 0) %>%
    mutate_if(is.numeric, funs((. + 1) / sum(. + 1))) %>%
    mutate(logratio = log(`5` / `1`)) %>%
    arrange(desc(logratio)) 

word_ratios %>% 
  mutate(pos_log_OR = ifelse(logratio > 0, "5 star > 1 star", "1 star > 5 star")) %>%
  group_by(pos_log_OR) %>%
  top_n(10, abs(logratio)) %>%
  ungroup() %>%
  mutate(word = fct_reorder(word, logratio)) %>%
  ggplot(aes(word, logratio, fill = pos_log_OR)) +
  geom_col() +
  coord_flip() +
  ylab("log odds ratio (5/1)") +
  scale_fill_discrete(name = "")
```

Sentiment analysis

```{r}
dynamite_word_sentiments <- dynamite_words %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(review_num, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  left_join(dynamite_reviews)
## Joining, by = "word"
## Joining, by = "review_num"

ggplot(dynamite_word_sentiments, 
       aes(x = reorder(review_num, -sentiment), 
           y = sentiment, fill = stars, color = stars)) + 
  geom_bar(stat = "identity") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_fill_viridis(direction = -1) + 
  scale_color_viridis(direction = -1) 
```

```{r}
#most positive review
dynamite_word_sentiments %>%
  filter(sentiment == max(sentiment)) %>% 
  pull(text)
```

```{r}
#most negative review
dynamite_word_sentiments %>%
  filter(sentiment == min(sentiment),
         stars == 1) %>% 
  pull(text)
```

